WIP: Try Vanilla 3.0 beta
canonical-web-and-design/react-components pull request #656
Opened 2021-11-25 15:16 UTC by bartaz

## Done

- Itemised list of what was changed by this PR.

## QA

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### QA steps

- Steps for QA.

## Fixes

Fixes: # .

2021-12-14 07:42 UTC, bartaz commented
Demo: https://react-components-656.demos.haus/?path=/story/accordion--default-story

2022-01-14 12:28 UTC, bethcollins92 requested changes
QA LGTM, just the query on the `p-button--undefined` class in the snapshot

2022-01-14 12:28 UTC, bethcollins92 commented on src/components/ActionButton/__snapshots__/ActionButton.test.tsx.snap
> +    className="p-action-button p-button--undefined is-processing"
I don't think this should be undefined

2022-01-14 14:13 UTC, bethcollins92 approved these changes
Go Go goooooo

2022-01-14 14:14 UTC, merged